// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhbvvcmxufrfhzuqlolf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoYnZ2Y214dWZyZmh6dXFsb2xmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNzc3NjYsImV4cCI6MjA1Nzk1Mzc2Nn0.baVY5oh75gqESUNb2Y6azCvNFv9WyDhF7U_fwQ_CKtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);